apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets-provider
spec:
  provider: azure
  secretObjects:
  - secretName: ao-secrets
    type: Opaque
    data:
    - key: CosmosDbConnectionString
      objectName: CosmosDbConnectionString
    - key: CosmosDbDatabaseName
      objectName: CosmosDbDatabaseName
    - key: CosmosDbProfileContainerName
      objectName: CosmosDbProfileContainerName
    - key: CosmosDbProgressContainerName
      objectName: CosmosDbProgressContainerName
    - key: EventHubConnectionString
      objectName: EventHubConnectionString
  parameters:
    usePodIdentity: "true"
    tenantId: ""
    keyvaultName: ""
    objects: |
      array:
        - |
          objectName: CosmosDbConnectionString
          objectType: secret
        - |
          objectName: CosmosDbDatabaseName
          objectType: secret
        - |
          objectName: CosmosDbProfileContainerName
          objectType: secret
        - |
          objectName: CosmosDbProgressContainerName
          objectType: secret
        - |
          objectName: EventHubConnectionString
          objectType: secret
