apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets-provider
spec:
  provider: azure
  secretObjects:
  - secretName: ao-secrets
    type: Opaque
    data:
    - key: AzureRegion
      objectName: AzureRegion
    - key: AppInsightsConnectionString
      objectName: AppInsightsConnectionString
    - key: CosmosDbConnectionString
      objectName: CosmosDbConnectionString
    - key: CosmosDbDatabaseName
      objectName: CosmosDbDatabaseName
    - key: CosmosDbProfileContainerName
      objectName: CosmosDbProfileContainerName
    - key: CosmosDbProgressContainerName
      objectName: CosmosDbProgressContainerName
    - key: StorageAccountConnString
      objectName: StorageAccountConnString
    - key: StorageAccountName
      objectName: StorageAccountName
    - key: StorageContainerName
      objectName: StorageContainerName
    - key: EventHubConnectionString
      objectName: EventHubConnectionString
    - key: EventHubName
      objectName: EventHubName
    - key: EventHubConsumerGroup
      objectName: EventHubConsumerGroup
    - key: EventHubReceiverBatchSize
      objectName: EventHubReceiverBatchSize
  parameters:
    usePodIdentity: "true"
    tenantId: ""
    keyvaultName: ""
    objects: |
      array:
        - |
          objectName: AzureRegion
          objectType: secret
        - |
          objectName: AppInsightsConnectionString
          objectType: secret
        - |
          objectName: CosmosDbConnectionString
          objectType: secret
        - |
          objectName: CosmosDbDatabaseName
          objectType: secret
        - |
          objectName: CosmosDbProfileContainerName
          objectType: secret
        - |
          objectName: CosmosDbProgressContainerName
          objectType: secret
        - |
          objectName: StorageAccountConnString
          objectType: secret
        - |
          objectName: StorageAccountName
          objectType: secret
        - |
          objectName: StorageContainerName
          objectType: secret
        - |
          objectName: EventHubConnectionString
          objectType: secret
        - |
          objectName: EventHubName
          objectType: secret
        - |
          objectName: EventHubConsumerGroup
          objectType: secret
        - |
          objectName: EventHubReceiverBatchSize
          objectType: secret
