apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets-provider
spec:
  provider: azure
  secretObjects:
    
  parameters:
    usePodIdentity: "true"
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"
    keyvaultName: "pz-ao-eastus-22"
    objects:  |
      array:
        - |
          objectName: CosmosDbConnectionString
          objectType: secret
        - |
          objectName: CosmosDbDatabaseName
          objectType: secret
        - |
          objectName: CosmosDbProfileContainerName
          objectType: secret
        - |
          objectName: CosmosDbProgressContainerName
          objectType: secret
        - |
          objectName: EventHubConnectionString
          objectType: secret
