apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    aadpodidbinding: pz-ao-eastus
spec:
  containers:
  - name: demo
    image: mcr.microsoft.com/oss/azure/aad-pod-identity/demo:v1.6.3
    args:
      - --subscriptionid=e61e4c75-268b-4c94-ad48-237aa3231481
      - --clientid=a5afdcc3-b7f5-4422-a655-1299ae0bae21
      - --resourcegroup=always-on-eastus
    env:
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
  nodeSelector:
    kubernetes.io/os: linux