apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: dns-chaos
  namespace: chaos-testing
spec:
  action: error
  mode: all
  patterns:
    - google.com
    - chaos-mesh.*
    - github.?om
    - microsoft.com
  selector:
    namespaces:
      - default
  duration: "90s"