apiVersion: chaos-mesh.org/v1alpha1
kind: IoChaos
metadata:
  name: io-delay
spec:
  action: fault
  mode: one
  value: ''
  selector:
    namespaces:
      - default
  volumePath: /var/run/etcd
  path: '/var/run/etcd/**/*'
  errno: 32
  percent: 50
  duration: '10s'
