apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-partition
  namespace: chaos-testing
spec:
  action: partition
  mode: one
  value: ''
  selector:
    namespaces:
      - default
  direction: to
  target:
    selector:
      namespaces:
        - default
    mode: one
  duration: "10s"