apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-duplicate
  namespace: chaos-testing
spec:
  action: duplicate
  mode: one
  value: ''
  selector:
    namespaces:
      - default
  duplicate:
    duplicate: "40"
    correlation: "25"
  duration: "10s"