apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay
  namespace: chaos-testing
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - default
  delay:
    latency: "90ms"
    correlation: "25"
    jitter: "90ms"
  duration: "10s"
