apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: burn-cpu
  namespace: chaos-testing
spec:
  mode: one
  value: ''
  selector:
    namespaces:
      - default
  stressors:
    cpu:
      workers: 1
      load: 100
  duration: "30s"