name: App-Deploy

on: 
  workflow_dispatch:

env:
  PREFIX: 'pz-ao'
  SUFFIX: '24'

jobs:
  deploy-app-in-region:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [eastus]
    steps:
      - name: Install Azure CLI extensions
        run: |
          az extension add --name aks-preview

      - name: Checkout repository
        if: success()
        uses: actions/checkout@v2

      - name: Azure login
        if: success()
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Prepare dynamic env vars
        if: success()
        run: |
          AZURE_RESOURCE_GROUP=always-on-${{ matrix.region }}
          AKS_CLUSTER_NAME=${{ env.PREFIX }}-${{ matrix.region }}
          VNET_NAME=${{ env.PREFIX }}-${{ matrix.region }}
          APP_NSG_NAME=app-${{ matrix.region }}

          echo "AZURE_RESOURCE_GROUP=$AZURE_RESOURCE_GROUP" >> $GITHUB_ENV
          echo "AKS_CLUSTER_NAME=$AKS_CLUSTER_NAME" >> $GITHUB_ENV
          echo "VNET_NAME=$VNET_NAME" >> $GITHUB_ENV
          echo "APP_NSG_NAME=$APP_NSG_NAME" >> $GITHUB_ENV


      - name: Set AKS Context
        if: success()
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          resource-group: '${{ env.AZURE_RESOURCE_GROUP }}'
          cluster-name: '${{ env.AKS_CLUSTER_NAME }}'

      - name: Deploy app to AKS
        if: success()
        uses: Azure/k8s-deploy@v1.4
        with:
          manifests: './src/workload-deploy/aks/azure-vote.yaml'
          kubectl-version: 'latest'
          force: true
          namespace: default


      - name: Azure logout
        run: |
          az logout
