name: App - Deploy

on: 
  workflow_dispatch:

env:
  PREFIX: 'pz-ao'
  SUFFIX: '18'

jobs:
  deploy-stamp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [northeurope]
    steps:
      - name: Install Azure CLI extensions
        run: |
          az extension add --name aks-preview

      - name: Checkout repository
        if: success()
        uses: actions/checkout@v2

      - name: Azure login
        if: success()
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Prepare dynamic env vars
        if: success()
        run: |
          AZURE_RESOURCE_GROUP=always-on-${{ matrix.region }}
          AKS_CLUSTER_NAME=${{ env.PREFIX }}-${{ matrix.region }}

          echo "AZURE_RESOURCE_GROUP=$AZURE_RESOURCE_GROUP" >> $GITHUB_ENV
          echo "AKS_CLUSTER_NAME=$AKS_CLUSTER_NAME" >> $GITHUB_ENV

      #- name: Get AKS credentials
      #  if: success()
      #  run: |
      #    az aks get-credentials --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} -g ${{ env.AZURE_RESOURCE_GROUP }} -n "${{ env.AKS_CLUSTER_NAME }}" --overwrite-existing --verbose

      #- name: Deploy app to AKS
      #  if: success()
      #  run: |
      #    kubectl apply -f ../../aks/azure-vote.yaml

      - name: Set AKS Context
        if: success()
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          resource-group: '${{ env.AZURE_RESOURCE_GROUP }}'
          cluster-name: '${{ env.AKS_CLUSTER_NAME }}'

      - name: Deploy app to AKS
        if: success()
        uses: Azure/k8s-deploy@v1.4
        with:
          manifests: 'aks/azure-vote.yaml'
          kubectl-version: 'latest'
          force: true

      - name: Azure logout
        run: |
          az logout
