name: App - Deploy

on: 
  workflow_dispatch:

env:
  PREFIX: 'pz-ao'
  SUFFIX: '18'

jobs:
  deploy-stamp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [northeurope]
    steps:
      - name: Install Azure CLI extensions
        run: |
          az extension add --name aks-preview

      - name: Checkout repository
        if: success()
        uses: actions/checkout@v2

      - name: Azure login
        if: success()
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Prepare dynamic env vars
        if: success()
        run: |
          AZURE_RESOURCE_GROUP=always-on-${{ matrix.region }}
          AKS_CLUSTER_NAME=${{ env.PREFIX }}-${{ matrix.region }}


      - name: Deploy app to AKS
        if: success()
        run: |
          az aks get-credentials --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} -g ${{ env.AZURE_RESOURCE_GROUP }} -n "${{ env.AKS_CLUSTER_NAME }}" --overwrite-existing --verbose
          kubectl apply -f ../../aks/azure-vote.yaml


      - name: Azure logout
        run: |
          az logout
