name: App-Deploy

on: 
  workflow_dispatch:

env:
  PREFIX: 'pz-ao'
  SUFFIX: '25'

  REGISTRY_REPO: ao
  BE_IMAGE_NAME: ao.be
  FE_IMAGE_NAME: ao.fe

  AKS_PATH_ROOT: './src/workload-deploy/aks/'

jobs:
  deploy-app-in-region:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [eastus]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        if: success()
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Prepare dynamic env vars
        if: success()
        run: |
          WORKLOAD_FILE_FE=${{ env.AKS_PATH_ROOT }}ao.fe.yaml
          WORKLOAD_FILE_BE=${{ env.AKS_PATH_ROOT }}ao.be.yaml
          WORKLOAD_FILE_SI=${{ env.AKS_PATH_ROOT }}ao.services-ingress.yaml

          AZURE_RESOURCE_GROUP=always-on-${{ matrix.region }}
          AKS_CLUSTER_NAME=${{ env.PREFIX }}-${{ matrix.region }}

          UAMI_NAME=${{ env.PREFIX }}-${{ matrix.region }}
          AKS_POD_IDENTITY_BINDING_SELECTOR=$UAMI_NAME-binding

          REGISTRY_NAME=${PREFIX//-/}${{ env.SUFFIX }}
          BE_FQDN=${REGISTRY_NAME}.azurecr.io/${REGISTRY_REPO}/${BE_IMAGE_NAME}
          FE_FQDN=${REGISTRY_NAME}.azurecr.io/${REGISTRY_REPO}/${FE_IMAGE_NAME}

          VNET_NAME=${{ env.PREFIX }}-${{ matrix.region }}
          APP_NSG_NAME=app-${{ matrix.region }}

          echo "WORKLOAD_FILE_FE=$WORKLOAD_FILE_FE" >> $GITHUB_ENV
          echo "WORKLOAD_FILE_BE=$WORKLOAD_FILE_BE" >> $GITHUB_ENV
          echo "WORKLOAD_FILE_SI=$WORKLOAD_FILE_SI" >> $GITHUB_ENV

          echo "AZURE_RESOURCE_GROUP=$AZURE_RESOURCE_GROUP" >> $GITHUB_ENV
          echo "AKS_CLUSTER_NAME=$AKS_CLUSTER_NAME" >> $GITHUB_ENV

          echo "UAMI_NAME=$UAMI_NAME" >> $GITHUB_ENV
          echo "AKS_POD_IDENTITY_BINDING_SELECTOR=$AKS_POD_IDENTITY_BINDING_SELECTOR" >> $GITHUB_ENV

          echo "REGISTRY_NAME=$REGISTRY_NAME" >> $GITHUB_ENV
          echo "BE_FQDN=$BE_FQDN" >> $GITHUB_ENV
          echo "FE_FQDN=$FE_FQDN" >> $GITHUB_ENV

          echo "VNET_NAME=$VNET_NAME" >> $GITHUB_ENV
          echo "APP_NSG_NAME=$APP_NSG_NAME" >> $GITHUB_ENV


      - name: Write Pod Identity Binding Selector to Back End YAML file
        if: success()
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: '${{ env.WORKLOAD_FILE_BE }}'
          propertyPath: 'spec.template.metadata.labels.aadpodidbinding'
          value: '${{ env.AKS_POD_IDENTITY_BINDING_SELECTOR }}'
          updateFile: 'true'
          commitChange: 'false'
          createPR: 'false'

      - name: Write Container Pull Source to Back End YAML file
        if: success()
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: '${{ env.WORKLOAD_FILE_BE }}'
          propertyPath: 'spec.template.spec.containers.0.image'
          value: '${{ env.BE_FQDN }}:latest'
          updateFile: 'true'
          commitChange: 'false'
          createPR: 'false'

      #- name: sed Back End YAML file container image URI
      #  if: success()
      #  run: |
      #    sed -i "s/REGISTRY_NAME/${{ env.REGISTRY_NAME }}/" ${{ env.WORKLOAD_FILE_BE }}

      - name: cat Back End YAML file
        if: success()
        run: |
          cat ${{ env.WORKLOAD_FILE_BE }}


      - name: Write Pod Identity Binding Selector to Front End YAML file
        if: success()
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: '${{ env.WORKLOAD_FILE_FE }}'
          propertyPath: 'spec.template.metadata.labels.aadpodidbinding'
          value: '${{ env.AKS_POD_IDENTITY_BINDING_SELECTOR }}'
          updateFile: 'true'
          commitChange: 'false'
          createPR: 'false'

      - name: Write Container Pull Source to Front End YAML file
        if: success()
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: '${{ env.WORKLOAD_FILE_FE }}'
          propertyPath: 'spec.template.spec.containers.0.image'
          value: '${{ env.FE_FQDN }}:latest'
          updateFile: 'true'
          commitChange: 'false'
          createPR: 'false'

      #- name: sed Front End YAML file container image URI
      #  if: success()
      #  run: |
      #    sed -i "s/REGISTRY_NAME/${{ env.REGISTRY_NAME }}/" ${{ env.WORKLOAD_FILE_FE }}

      - name: cat Front End YAML file
        if: success()
        run: |
          cat ${{ env.WORKLOAD_FILE_FE }}


      - name: Set AKS Context
        if: success()
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          resource-group: '${{ env.AZURE_RESOURCE_GROUP }}'
          cluster-name: '${{ env.AKS_CLUSTER_NAME }}'

      - name: Deploy Back End to AKS
        if: success()
        uses: Azure/k8s-deploy@v1.4
        with:
          manifests: '${{ env.WORKLOAD_FILE_BE }}'
          kubectl-version: 'latest'
          force: true
          namespace: default

      - name: Deploy Front End to AKS
        if: success()
        uses: Azure/k8s-deploy@v1.4
        with:
          manifests: '${{ env.WORKLOAD_FILE_FE }}'
          kubectl-version: 'latest'
          force: true
          namespace: default

      - name: Deploy Services and Ingress to AKS
        if: success()
        uses: Azure/k8s-deploy@v1.4
        with:
          manifests: '${{ env.WORKLOAD_FILE_SI }}'
          kubectl-version: 'latest'
          force: true
          namespace: default


      - name: Azure logout
        run: |
          az logout
