name: Delete Azure environment

on: 
  workflow_dispatch:

jobs:
  delete-stamp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [centralus, westus2]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Destroy regional stamp Resource Group
        if: success()
        run: |
          AZURE_RESOURCE_GROUP=always-on-${{ matrix.region }}
          az group delete --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}} --name $AZURE_RESOURCE_GROUP --yes

      - name: Azure logout
        run: |
          az logout
