name: Delete Azure environment

on: 
  workflow_dispatch:
  pull_request:
    types: [labeled]

env:
  AZURE_RESOURCE_GROUP: always-on-eus
  AZURE_LOCATION: '"East US"'

jobs:
  delete-azure-resources:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'delete')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Destroy Azure environment
        if: success()
        run: |
          az group delete --name ${{env.AZURE_RESOURCE_GROUP}} --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}} --yes