name: Deploy Region Stamp

on: 
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP_GLOBAL: 'always-on-global'
  LA_WORKSPACE_NAME: 'pz-ao'


jobs:
  rgs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [eastus]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        if: success()
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Prepare dynamic env vars
        if: success()
        run: |
          echo "AZURE_RESOURCE_GROUP=always-on-${{ matrix.region }}" >> $GITHUB_ENV
          echo "KEY_VAULT_NAME=pz-ao-${{ matrix.region }}" >> $GITHUB_ENV
          echo "VNET_NAME=pz-ao-${{ matrix.region }}" >> $GITHUB_ENV
          echo "EVENT_HUB_NS_NAME=pz-ao-${{ matrix.region }}" >> $GITHUB_ENV
          echo "AKS_CLUSTER_NAME=pz-ao-${{ matrix.region }}" >> $GITHUB_ENV
          echo "AKS_DNS_PREFIX=pzao${{ matrix.region }}" >> $GITHUB_ENV
          echo "APPGW_NAME=pz-ao-${{ matrix.region }}" >> $GITHUB_ENV
          echo "APPGW_PUBLIC_IP_NAME=pz-ao-appgw-${{ matrix.region }}" >> $GITHUB_ENV
          echo "APIM_SERVICE_NAME=pz-ao-apim-${{ matrix.region }}" >> $GITHUB_ENV
          echo "APIM_PUBLIC_IP_NAME=pz-ao-apim-${{ matrix.region }}" >> $GITHUB_ENV
          echo "AZURE_RESOURCE_GROUP_AKS_NODES=$AZURE_RESOURCE_GROUP-$AKS_CLUSTER_NAME" >> $GITHUB_ENV
          echo "LA_WORKSPACE_ID=$(az monitor log-analytics workspace show --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}} -g ${{env.AZURE_RESOURCE_GROUP_GLOBAL}} -n ${{env.LA_WORKSPACE_NAME}} -o tsv --query 'id')" >> $GITHUB_ENV

      #- name: Install CLI extensions
      #  if: success()
      #  run: |
      #    az extension add --name aks-preview

      - name: Create Azure resource group
        if: success()
        run: |
          az group create --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --location ${{ matrix.region }} --name ${{ env.AZURE_RESOURCE_GROUP }}

      - name: Azure logout
        run: |
          az logout
