name: Infra-ConfigRegion

on: 
  workflow_dispatch:

env:
  PREFIX: 'pz-ao'
  SUFFIX: '22'

  AZURE_RESOURCE_GROUP_GLOBAL: 'always-on-global'

  COSMOS_DB_DATABASE_NAME: 'ao'
  COSMOS_DB_CONTAINER_1_NAME: 'profiles'
  COSMOS_DB_CONTAINER_2_NAME: 'progress'

  EVENT_HUB_AUTH_RULE_NAME: 'SendListen'

  SECRET_NAME_COSMOS_DB_CONN_STRING: 'CosmosDbConnectionString'
  SECRET_NAME_COSMOS_DB_DATABASE_NAME: 'CosmosDbDatabaseName'
  SECRET_NAME_COSMOS_DB_CONTAINER_1_NAME: 'CosmosDbProfileContainerName'
  SECRET_NAME_COSMOS_DB_CONTAINER_2_NAME: 'CosmosDbProgressContainerName'
  SECRET_NAME_EVENT_HUB_NS_CONN_STRING: 'EventHubConnectionString'

jobs:
  deploy-region:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [eastus]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        if: success()
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Prepare dynamic env vars
        if: success()
        run: |
          AZURE_RESOURCE_GROUP=always-on-${{ matrix.region }}
          COSMOS_DB_ACCT_NAME=${{ env.PREFIX }}
          KEY_VAULT_NAME=${{ env.PREFIX }}-${{ matrix.region }}-${{ env.SUFFIX }}
          EVENT_HUB_NS_NAME=${{ env.PREFIX }}-${{ matrix.region }}
          AKS_CLUSTER_NAME=${{ env.PREFIX }}-${{ matrix.region }}

          echo "AZURE_RESOURCE_GROUP=$AZURE_RESOURCE_GROUP" >> $GITHUB_ENV
          echo "COSMOS_DB_ACCT_NAME=$COSMOS_DB_ACCT_NAME" >> $GITHUB_ENV
          echo "KEY_VAULT_NAME=$KEY_VAULT_NAME" >> $GITHUB_ENV
          echo "EVENT_HUB_NS_NAME=$EVENT_HUB_NS_NAME" >> $GITHUB_ENV
          echo "AKS_CLUSTER_NAME=$AKS_CLUSTER_NAME" >> $GITHUB_ENV

      - name: Prepare dynamic env vars 2
        if: success()
        run: |
          echo "COSMOS_DB_CONN_STRING=$(az cosmosdb keys list --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} -g ${{ env.AZURE_RESOURCE_GROUP_GLOBAL }} -n ${{ env.COSMOS_DB_ACCT_NAME }} --type connection-strings -o tsv --query 'connectionStrings[0].connectionString')" >> $GITHUB_ENV
          echo "EVENT_HUB_NS_CONN_STRING=$(az eventhubs namespace authorization-rule keys list --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} -g ${{ env.AZURE_RESOURCE_GROUP }} --namespace-name ${{ env.EVENT_HUB_NS_NAME }} -n ${{ env.EVENT_HUB_AUTH_RULE_NAME }} -o tsv --query 'primaryConnectionString')" >> $GITHUB_ENV


      - name: Write secrets to region Key Vault
        if: success()
        run: |
          az keyvault secret set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --vault-name ${{ env.KEY_VAULT_NAME }} --name ${{ env.SECRET_NAME_COSMOS_DB_CONN_STRING }} --value "${{ env.COSMOS_DB_CONN_STRING }}"
          az keyvault secret set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --vault-name ${{ env.KEY_VAULT_NAME }} --name ${{ env.SECRET_NAME_COSMOS_DB_DATABASE_NAME }} --value "${{ env.COSMOS_DB_DATABASE_NAME }}"
          az keyvault secret set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --vault-name ${{ env.KEY_VAULT_NAME }} --name ${{ env.SECRET_NAME_COSMOS_DB_CONTAINER_1_NAME }} --value "${{ env.COSMOS_DB_CONTAINER_1_NAME }}"
          az keyvault secret set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --vault-name ${{ env.KEY_VAULT_NAME }} --name ${{ env.SECRET_NAME_COSMOS_DB_CONTAINER_2_NAME }} --value "${{ env.COSMOS_DB_CONTAINER_2_NAME }}"
          az keyvault secret set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --vault-name ${{ env.KEY_VAULT_NAME }} --name ${{ env.SECRET_NAME_EVENT_HUB_NS_CONN_STRING }} --value "${{ env.EVENT_HUB_NS_CONN_STRING }}"


      #- name: Set AKS Context
      #  if: success()
      #  uses: azure/aks-set-context@v1
      #  with:
      #    creds: '${{ secrets.AZURE_CREDENTIALS }}'
      #    resource-group: '${{ env.AZURE_RESOURCE_GROUP }}'
      #    cluster-name: '${{ env.AKS_CLUSTER_NAME }}'

      #- name: Deploy Namespace
      #  if: success()
      #  uses: Azure/k8s-deploy@v1.4
      #  with:
      #    manifests: './src/infra-deploy/aks/namespace.yaml'
      #    kubectl-version: 'latest'
      #    force: true

      #- name: Deploy Secrets Store CSI Driver 1/6
      #  if: success()
      #  uses: Azure/k8s-deploy@v1.4
      #  with:
      #    manifests: 'https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/deploy/rbac-secretproviderclass.yaml'
      #    kubectl-version: 'latest'
      #    force: true

      #- name: Deploy Secrets Store CSI Driver 2/6
      #  if: success()
      #  uses: Azure/k8s-deploy@v1.4
      #  with:
      #    manifests: 'https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/deploy/csidriver.yaml'
      #    kubectl-version: 'latest'
      #    force: true

      #- name: Deploy Secrets Store CSI Driver 3/6
      #  if: success()
      #  uses: Azure/k8s-deploy@v1.4
      #  with:
      #    manifests: 'https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml'
      #    kubectl-version: 'latest'
      #    force: true

      #- name: Deploy Secrets Store CSI Driver 4/6
      #  if: success()
      #  uses: Azure/k8s-deploy@v1.4
      #  with:
      #    manifests: 'https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml'
      #    kubectl-version: 'latest'
      #    force: true

      #- name: Deploy Secrets Store CSI Driver 5/6
      #  if: success()
      #  uses: Azure/k8s-deploy@v1.4
      #  with:
      #    manifests: 'https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/deploy/secrets-store-csi-driver.yaml'
      #    kubectl-version: 'latest'
      #    force: true

      #- name: Deploy Secrets Store CSI Driver 6/6
      #  if: success()
      #  uses: Azure/k8s-deploy@v1.4
      #  with:
      #    manifests: 'https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/deploy/rbac-secretprovidersyncing.yaml'
      #    kubectl-version: 'latest'
      #    force: true

      #- name: Deploy AKS Provider for Secrets Store CSI Driver
      #  if: success()
      #  uses: Azure/k8s-deploy@v1.4
      #  with:
      #    manifests: 'https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/deployment/provider-azure-installer.yaml'
      #    kubectl-version: 'latest'
      #    force: true

      #- name: Deploy SecretProviderClass
      #  if: success()
      #  uses: Azure/k8s-deploy@v1.4
      #  with:
      #    manifests: 'src/infra-deploy/aks/secret-store.akv.yaml'
      #    kubectl-version: 'latest'
      #    force: true


      - name: Azure logout
        run: |
          az logout
