name: Shared.Infra.Deploy

on: 
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP_SHARED: 'ao-shared'
  AZURE_LOCATION_SHARED: 'eastus2'

jobs:
  single:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        if: success()
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Azure resource group
        if: success()
        run: |
          az group create --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --location ${{ env.AZURE_LOCATION_SHARED }} --name ${{ env.AZURE_RESOURCE_GROUP_SHARED }}

      - name: Azure logout
        run: |
          az logout


  per-region:
    needs: single
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [eastus2,westus2]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        if: success()
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Network Watcher
        if: success()
        uses: azure/arm-deploy@main
        with:
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_SHARED }}
          template: ./src/infra-deploy/templates/net.network-watcher.json
          parameters: location=${{ matrix.region }} networkWatcherName="NetworkWatcher_""${{ matrix.region }}"

      - name: Azure logout
        run: |
          az logout
