name: Test Env Var

on:
  workflow_dispatch:
  push:
    branches:
      - test

env:
  PREFIX: 'pz-ao'
  SUFFIX: '18'
  NAME_1: '$PREFIX-MyName1-$SUFFIX'
  NAME_2: '$PREFIX-MyName2-$SUFFIX'

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo env vars
        run: |
          echo $PREFIX
          echo $SUFFIX
          echo ${{ env.NAME_1 }}
          echo ${{ env.NAME_2 }}

      - name: Prep dynamic env var
        run: |
          echo "TEST_VAR=${PREFIX//-/}${{ env.SUFFIX }}" >> $GITHUB_ENV

      #- name: Echo dynamic env var
      #  run: |
      #    echo "${{ env.TEST_VAR }}"
