name: Test env var concatenation

on: push

env:
  INFIX: 'foo'
  NAME_1: MyName1-$INFIX
  NAME_2: MyName2-$INFIX

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Envvar
        run: |
          echo ${{env.NAME_1}}
          echo ${{env.NAME_2}}
