name: Test Env Var

on:
  workflow_dispatch:
  push:
    branches:
      - test

env:
  PREFIX: 'pz-ao'
  SUFFIX: '18'
  FRONT_DOOR_NAME: 'fd'

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      #- name: Echo env vars
      #  run: |
      #    echo $PREFIX
      #    echo $SUFFIX
      #    echo ${{ env.UAMI_NAME }}
      #    echo ${{ env.NAME_1 }}
      #    echo ${{ env.NAME_2 }}

      - name: Prep dynamic env vars
        run: |
          echo "NAME_1=${{ env.PREFIX }}-MyName1-${{ env.SUFFIX }}" >> $GITHUB_ENV
          echo "NAME_2=${{ env.PREFIX }}-MyName2-${{ env.SUFFIX }}" >> $GITHUB_ENV
          echo "UAMI_NAME=${{ env.PREFIX }}-uami" >> $GITHUB_ENV
          echo "REGISTRY_NAME=${PREFIX//-/}${{ env.SUFFIX }}" >> $GITHUB_ENV
          echo "FD_WAF_POLICY_NAME=${FRONT_DOOR_NAME//-/}" >> $GITHUB_ENV
          echo "FRONT_DOOR_ENDPOINT_NAME=${FRONT_DOOR_NAME//-/}" >> $GITHUB_ENV

      - name: Echo dynamic env vars
        run: |
          echo "${{ env.NAME_1 }}"
          echo "${{ env.NAME_2 }}"
          echo "${{ env.UAMI_NAME }}"
          echo "${{ env.REGISTRY_NAME }}"
          echo "${{ env.FD_WAF_POLICY_NAME }}"
          echo "${{ env.FRONT_DOOR_ENDPOINT_NAME }}"
