name: Test env var concatenation and substring

on: push

env:
  INFIX: 'foo'
  NAME_1: MyName1-$INFIX
  NAME_2: MyName2-$INFIX

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare a new env var based on env value
        env:
          NAME_1_SHORT: ${NAME_1:0:3}

  test2:
    runs-on: ubuntu-latest
    steps:
      - name: Echo out the env vars in a new job
        run: |
          echo ${{env.NAME_1}}
          echo ${{env.NAME_2}}
          echo ${{env.NAME_1_SHORT}}
